# Generated by Django 4.2.5 on 2023-10-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_id",
                    models.CharField(default=None, max_length=100, unique=True),
                ),
                ("value", models.CharField(max_length=100)),
                ("result", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(default=None, max_length=100, unique=True),
                ),
                (
                    "cells",
                    models.ManyToManyField(
                        blank=True, related_name="cells", to="v1.cell"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cell",
            name="sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheets",
                to="v1.sheet",
            ),
        ),
    ]
