name: Codecov workflow
on: [ push ]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.11'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pip install requests
          pip install responses
          pip install django
      - name: Run Tests
        run: |
          DJANGO_SETTINGS_MODULE=excelledAPI.settings pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 63677f1d-31b2-43c3-b3a6-da73c01c4d09
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
